config/routes.rb
Smarket::Application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "home/datoscuenta"
  get "home/comovender"
  get "home/comocomprar"
  get "home/perfil"
  get "home/about"
  get "home/contacto"
  get "home/terminos"
  get "home/index"
  resources :tipo_transaccions

  resources :producto_rematados

  resources :provincia_units

  resources :propiedadclases

  resources :compra_venta_normals

  resources :clase_units

  resources :prod_of_necs

  resources :compra_venta_especials

  resources :producto_necesitados

  resources :compra_remates

  resources :notificacions

  resources :comisions

  resources :remates

  resources :pujas

  resources :valors

  resources :usuarios

  resources :propiedads

  resources :regions

  resources :productos

  resources :estado_remates

  resources :ganancia_liquidas

  resources :est_prod_of_necs

  resources :estado_notificacions

  resources :producto_ofertados

  resources :comunas

  resources :condicions


  root :to => "home#index"
  devise_for :usuarios, :controllers => { registrations: 'registrations' }, :skip => [:sessions, :registrations] 
  as :usuario do
    get    "entrar",  to: "devise/sessions#new",         :as => :new_usuario_session
    post   "entrar",  to: "devise/sessions#create",      :as => :usuario_session
    delete "salir", to: "devise/sessions#destroy",     :as => :destroy_usuario_session
 
    get    "registrarse",  to: "devise/registrations#new",    :as => :new_usuario_registration
    post   "registrarse",  to: "devise/registrations#create", :as => :usuario_registration
  end
  
  
end

app/models/notificacion.rb
class Notificacion < ActiveRecord::Base
  self.table_name = 'notificacion'
  self.primary_key = 'notificacion_id '
  belongs_to :usuario
  belongs_to :estado_not
end

app/controllers/notificacions_controller.rb
class NotificacionsController < ApplicationController
  before_action :set_notificacion, only: [:show, :edit, :update, :destroy]

  # GET /notificacions
  # GET /notificacions.json
  def index
    @notificacions = Notificacion.all
  end

  # GET /notificacions/1
  # GET /notificacions/1.json
  def show
  end

  # GET /notificacions/new
  def new
    @notificacion = Notificacion.new
  end

  # GET /notificacions/1/edit
  def edit
  end

  # POST /notificacions
  # POST /notificacions.json
  def create
    @notificacion = Notificacion.new(notificacion_params)

    respond_to do |format|
      if @notificacion.save
        format.html { redirect_to @notificacion, notice: 'Notificacion was successfully created.' }
        format.json { render action: 'show', status: :created, location: @notificacion }
      else
        format.html { render action: 'new' }
        format.json { render json: @notificacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notificacions/1
  # PATCH/PUT /notificacions/1.json
  def update
    respond_to do |format|
      if @notificacion.update(notificacion_params)
        format.html { redirect_to @notificacion, notice: 'Notificacion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notificacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notificacions/1
  # DELETE /notificacions/1.json
  def destroy
    @notificacion.destroy
    respond_to do |format|
      format.html { redirect_to notificacions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notificacion
      @notificacion = Notificacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notificacion_params
      params.require(:notificacion).permit(:notificacion_id, :usuario_id, :estado_not_id, :notificacio_titulo, :notificacion_texto)
    end
end

app/helpers/notificacions_helper.rb
module NotificacionsHelper
end

app/views/notificacions/_form.html.erb
<%= form_for(@notificacion) do |f| %>
  <% if @notificacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notificacion.errors.count, "error") %> prohibited this notificacion from being saved:</h2>

      <ul>
      <% @notificacion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notificacion_id %><br>
    <%= f.text_field :notificacion_id %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.text_field :usuario_id %>
  </div>
  <div class="field">
    <%= f.label :estado_not_id %><br>
    <%= f.text_field :estado_not_id %>
  </div>
  <div class="field">
    <%= f.label :notificacio_titulo %><br>
    <%= f.text_field :notificacio_titulo %>
  </div>
  <div class="field">
    <%= f.label :notificacion_texto %><br>
    <%= f.text_field :notificacion_texto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notificacions/edit.html.erb
<h1>Editing notificacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @notificacion %> |
<%= link_to 'Back', notificacions_path %>

app/views/notificacions/index.html.erb
<h1>Listing notificacions</h1>

<table>
  <thead>
    <tr>
      <th>Notificacion</th>
      <th>Usuario</th>
      <th>Estado not</th>
      <th>Notificacio titulo</th>
      <th>Notificacion texto</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notificacions.each do |notificacion| %>
      <tr>
        <td><%= notificacion.notificacion %></td>
        <td><%= notificacion.usuario %></td>
        <td><%= notificacion.estado_not %></td>
        <td><%= notificacion.notificacio_titulo %></td>
        <td><%= notificacion.notificacion_texto %></td>
        <td><%= link_to 'Show', notificacion %></td>
        <td><%= link_to 'Edit', edit_notificacion_path(notificacion) %></td>
        <td><%= link_to 'Destroy', notificacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notificacion', new_notificacion_path %>

app/views/notificacions/new.html.erb
<h1>New notificacion</h1>

<%= render 'form' %>

<%= link_to 'Back', notificacions_path %>

app/views/notificacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Notificacion:</strong>
  <%= @notificacion.notificacion %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @notificacion.usuario %>
</p>

<p>
  <strong>Estado not:</strong>
  <%= @notificacion.estado_not %>
</p>

<p>
  <strong>Notificacio titulo:</strong>
  <%= @notificacion.notificacio_titulo %>
</p>

<p>
  <strong>Notificacion texto:</strong>
  <%= @notificacion.notificacion_texto %>
</p>

<%= link_to 'Edit', edit_notificacion_path(@notificacion) %> |
<%= link_to 'Back', notificacions_path %>