config/routes.rb
Smarket::Application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "home/datoscuenta"
  get "home/comovender"
  get "home/comocomprar"
  get "home/perfil"
  get "home/about"
  get "home/contacto"
  get "home/terminos"
  get "home/index"
  resources :tipo_transaccions

  resources :producto_rematados

  resources :provincia_units

  resources :propiedadclases

  resources :compra_venta_normals

  resources :clase_units

  resources :prod_of_necs

  resources :compra_venta_especials

  resources :producto_necesitados

  resources :compra_remates

  resources :notificacions

  resources :comisions

  resources :remates

  resources :pujas

  resources :valors

  resources :usuarios

  resources :propiedads

  resources :regions

  resources :productos

  resources :estado_remates

  resources :ganancia_liquidas

  resources :est_prod_of_necs

  resources :estado_notificacions

  resources :producto_ofertados

  resources :comunas

  resources :condicions


  root :to => "home#index"
  devise_for :usuarios, :controllers => { registrations: 'registrations' }, :skip => [:sessions, :registrations] 
  as :usuario do
    get    "entrar",  to: "devise/sessions#new",         :as => :new_usuario_session
    post   "entrar",  to: "devise/sessions#create",      :as => :usuario_session
    delete "salir", to: "devise/sessions#destroy",     :as => :destroy_usuario_session
 
    get    "registrarse",  to: "devise/registrations#new",    :as => :new_usuario_registration
    post   "registrarse",  to: "devise/registrations#create", :as => :usuario_registration
  end
  
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/clase_unit.rb
class ClaseUnit < ActiveRecord::Base
  self.table_name = 'clase_unit'
  self.primary_key = 'clase_id'

  has_many :subcategorias, :class_name => "ClaseUnit", :foreign_key => "cla_clase_id", :dependent => :destroy
  belongs_to :categoria_padre, :class_name => "ClaseUnit"
  belongs_to :producto, :class_name => "Producto"
  has_many :propiedad_clases, :class_name => "Propiedadclase"

end

app/models/comision.rb
class Comision < ActiveRecord::Base
  self.table_name = 'comision'
  self.primary_key = 'comision_id'
  belongs_to :transaccion
end

app/models/compra_remate.rb
class CompraRemate < ActiveRecord::Base
  self.table_name = 'compra_remate'
  self.primary_key = 'comprasubasta_id'
  #inherits_from :tipo_transaccion
  belongs_to :usuario
  belongs_to :prod_sub
  belongs_to :usu_usuario , :class_name => "Usuario"
end

app/models/comuna.rb
class Comuna < ActiveRecord::Base
  self.table_name = 'comuna'
  self.primary_key = 'comuna_id'
  has_many :usuarios, :class_name => "Usuario"
  belongs_to :provincia
end

app/models/condicion.rb
class Condicion < ActiveRecord::Base
  self.table_name = 'condicion'
  self.primary_key = 'condicion_id'
  belongs_to :tipo_trans
end

app/models/estado_remate.rb
class EstadoRemate < ActiveRecord::Base
  self.table_name = 'estado_remate'
  self.primary_key = 'estado_subasta_id'
  has_many :remates, :class_name => "Remate"
end

app/models/notificacion.rb
class Notificacion < ActiveRecord::Base
  self.table_name = 'notificacion'
  self.primary_key = 'notificacion_id '
  belongs_to :usuario
  belongs_to :estado_not
end

app/models/prod_of_nec.rb
class ProdOfNec < Producto
  self.table_name = 'prod_of_nec'
  self.primary_key = 'prod_of_nec_id'
 #inherits_from :producto
  belongs_to :usuario
  belongs_to :estado_prod_of_necesidad
  belongs_to :prod_nec
  belongs_to :compra_venta_normal
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  mount_uploader :avatar, FotoUploader	
  self.table_name = 'producto'
  self.primary_key = 'producto_id'
  has_many :producto_ofertados, :dependent => :destroy,:class_name => "ProductoOfertado"
  accepts_nested_attributes_for :producto_ofertados
  #acts_as_superclass, :subtype => 'producto_necesitado', :subtype => 'producto_rematado', :subtype => 'producto_ofertado', :subtype => 'prod_of_nec'
  belongs_to :valor, :class_name => "Valor"
  has_many :clases, :class_name => "Clase", :foreign_key => "clase_id"


end

app/models/propiedad.rb
class Propiedad < ActiveRecord::Base
  self.table_name = 'propiedad'
  self.primary_key = 'id'
  belongs_to :propiedad
end

app/models/propiedadclase.rb
class Propiedadclase < ActiveRecord::Base
  self.table_name = 'propiedadclase'
  self.primary_key = 'id'
  belongs_to :propiedad
  belongs_to :clase
end

app/models/puja.rb
class Puja < ActiveRecord::Base
  self.table_name = 'puja'
  self.primary_key = 'puja_id'
  belongs_to :sub
  belongs_to :usuario
end

app/models/region.rb
class Region < ActiveRecord::Base
  self.table_name = 'region'
  self.primary_key = 'region_id'
  has_many :provincia_units
  belongs_to :region
end

app/models/remate.rb
class Remate < ActiveRecord::Base
  self.table_name = 'remate'
  self.primary_key = 'id'
  has_many :pujas, :class_name => "Puja"
  belongs_to :estado_subasta
  belongs_to :usuario
  belongs_to :prod_sub
end

app/models/transaccion.rb
class Transaccion < ActiveRecord::Base
  self.table_name = 'transaccion'
  self.primary_key = 'transaccion_id'
  belongs_to :tipo_trans
  has_one :comision
  has_one :ganancia

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  include ActiveModel::Validations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  self.table_name = 'usuario'
  self.primary_key = 'usuario_id'
  validates :usuario_nombre_usuario, :presence => true
  validates :usuario_rut, :presence => true
  validates :usuario_rut, rut: true
  validates :usuario_nombre, :presence => true
  validates :usuario_apellidopat, :presence => true
  validates :usuario_apellidomat, :presence => true
  
  validates :email, :presence => true
  validates :usuario_calle, :presence => true
  validates :usuario_numero_calle, :presence => true
  validates :usuario_villa, :presence => true

  has_many :notificaciones, :class_name => "Notificacion"
  has_many :producto_necesitados, :class_name => "ProductoNecesitado"
  has_many :pujas, :class_name =>"Puja"
  has_many :producto_ofertados
  has_many :compra_venta_normales
  has_many :compra_venta_especiales



end

app/models/valor.rb
class Valor < ActiveRecord::Base
  self.table_name = 'valor'
  self.primary_key = 'valor_id'
  belongs_to :propiedad
  belongs_to :producto
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def datoscuenta
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pujas_helper.rb
module PujasHelper
end

app/helpers/valors_helper.rb
module ValorsHelper
end

app/views/home/about.html.erb
       <div class="login">
          <div class="wrap">
				<ul class="breadcrumb breadcrumb__t"><%= link_to "Home", root_path, {:style => 'background:#f7f7f7'} %>  / Sobre nosotros</ul>
				<div class="section group">
				   <div class="labout span_1_of_about">
					 <h3>Testimonios</h3>
					  <div class="testimonials ">
						<div class="testi-item">
						<blockquote class="testi-item_blockquote">
							<a href="#", style='background:#f7f7f7;'>Antes de Smarket no confiaba en realizar compras a través de Internet, pensaba que mis productos vendrían defectuosos y nadie respondería. Gracias Smarket por prestar un servicio de calidad y al alcance de las personas </a>
							<div class="clear"></div>
						</blockquote>
							<small class="testi-meta"><span class="user">Joaquín Flores</span>
							</small></div>
					   </div>
					   <div class="testimonials ">
						<div class="testi-item">
						<blockquote class="testi-item_blockquote">
							<a href="#", style='background:#f7f7f7;'>Gracias a Smarket pude encontrar productos que en las tiendas es imposible o están a precios muy elevados, el servicio es rápido y confiable </a>
							<div class="clear"></div>
						</blockquote>
							<small class="testi-meta"><span class="user">Luis Cárcamo</span>
							</small></div>
					   </div>
				    </div>
				    <div class="cont span_2_of_about">
				       <h3>Sobre nosotros</h3>
					   	<p>Smarket es una empresa líder en el mercado en cuanto a compra y venta de productos online. Detrás de nuestra empresa, se encuentra un equipo de gente especializada que estará siempre dispuesta a ayudar y servir a la comunidad de compradores y vendedores de nuestra página. Como equipo nos comprometemos a dar un servicio de calidad y 100% confiable.</p>
						<br>
						<h3>Nuestra misión</h3>
						<p>La razón de ser de Smarket es facilitar a los usuarios de nuestro sistema realizar la compra y venta de sus productos de manera ágil y dentro de un entorno seguro y confiable, ademas de proporcionarles todas las herramientas necesarias para cumplir este próposito. Como empresa nos comprometemos siempre a responder ante las dudas de nuestros clientes.</p>
				        
							
		   </div>
		   <!-- Add fancyBox main JS and CSS files -->
		<script src="js/jquery.magnific-popup.js" type="text/javascript"></script>
		<link href="css/magnific-popup.css" rel="stylesheet" type="text/css">
		<script>
			$(document).ready(function() {
				$('.popup-with-zoom-anim').magnificPopup({
					type: 'inline',
					fixedContentPos: false,
					fixedBgPos: true,
					overflowY: 'auto',
					closeBtnInside: true,
					preloader: false,
					midClick: true,
					removalDelay: 300,
					mainClass: 'my-mfp-zoom-in'
			});
		});
		</script>
           </div>
		   <div class="clear"></div>	
		  </div>
	</div>	
   </div> 

app/views/home/comocomprar.html.erb
       <div class="login">
          <div class="wrap">
				<ul class="breadcrumb breadcrumb__t"><%= link_to "Home", root_path, {:style => 'background:#f7f7f7'} %>  / Cómo Comprar </ul>

				    <div class="cont span_2_of_about">
				       <h3>Cómo comprar un producto</h3>
				       <p>Pasos para comprar un producto:
				       <br>1. Buscar el producto que se necesita.
				       <br>2. Una vez encontrado dicho producto se selecciona para la compra.
				       <br>3. Se elige el medio de pago de dicho producto.
				       <br>4. Coordina la entrega del producto con el vendedor.
				       <br>5. Una vez realizada la compra del producto avisanos para concretar satisfactoriamente la transacción.
			       	   </p>

				       <h3>Cómo participar en una subasta</h3>
				       <p>Una vez encontrado un producto dentro de una subasta, haz clic en 'Pujar'.
				       <br>Luego debes ingresar una cantidad mayor a la última puja hecha en ese producto.
					   <br>Después debes hacer clic en 'Confirmar' para pujar por dicho producto.
				       <br>Si alguien realiza una oferta mayor a la que tu pujaste, te lo haremos saber mediante un e-mail.
				       <br>En el caso que ganes la subasta, te lo haremos saber mediante un e-mail.
				       <h3>Cómo publicar una necesidad</h3>
					   <p>Primero debes seleccionar la categoría en la cual pertenece el producto necesitado.
				       <br>Luego debes ingresar los detalles y especificaciones que deseas que tenga el producto y tambien el precio máximo a pagar por él.
					   <br>Después debes hacer clic en 'Confirmar' para publicar dicha necesidad.
				       <br>Si alguien realiza una oferta para tu producto, te lo haremos saber mediante un e-mail.
				       <br>Tienes la opción para cancelar o aceptar las ofertas que vas recibiendo.
				       </p>
		   </div>
		   <!-- Add fancyBox main JS and CSS files -->
		<script src="js/jquery.magnific-popup.js" type="text/javascript"></script>
		<link href="css/magnific-popup.css" rel="stylesheet" type="text/css">
		<script>
			$(document).ready(function() {
				$('.popup-with-zoom-anim').magnificPopup({
					type: 'inline',
					fixedContentPos: false,
					fixedBgPos: true,
					overflowY: 'auto',
					closeBtnInside: true,
					preloader: false,
					midClick: true,
					removalDelay: 300,
					mainClass: 'my-mfp-zoom-in'
			});
		});
		</script>
           </div>
		   <div class="clear"></div>	
		  </div>
	</div>	
   </div> 

app/views/home/comovender.html.erb
       <div class="login">
          <div class="wrap">
				<ul class="breadcrumb breadcrumb__t"><%= link_to "Home", root_path, {:style => 'background:#f7f7f7'} %>  / Cómo Vender </ul>

				    <div class="cont span_2_of_about">
				       <h3>Cómo vender un producto</h3>
				       <p>Primero debes seleccionar la categoría en la cual pertenece tu producto a ofertar.
				       <br>Luego debes ingresar los detalles del producto, ya sea su precio, nombre y resumen del producto.
					   <br>Después debes hacer clic en 'Confirmar' para ofertar dicho producto.
				       <br>Si alguien realiza una compra de tu producto, te lo haremos saber mediante un e-mail.
				       </p>
					   <h3>Cómo subastar un producto</h3>
				       <p>Primero debes seleccionar la categoría en la cual pertenece tu producto a subastar.
				       <br>Luego debes ingresar los detalles del producto, ya sea su precio base, nombre y resumen del producto.
				       <br>Tambien se debe seleccionar el tiempo de duración de la subasta.
					   <br>Después debes hacer clic en 'Subastar' para subastar dicho producto.
				       <br>Si alguien realiza una puja de tu producto, te lo haremos saber mediante un e-mail.
				       <br>Al finalizar la subasta, te enviaremos un e-mail con el nombre del usuario ganador y el precio por que cual pujó.
				       </p>
				    
		   </div>
		   <!-- Add fancyBox main JS and CSS files -->
		<script src="js/jquery.magnific-popup.js" type="text/javascript"></script>
		<link href="css/magnific-popup.css" rel="stylesheet" type="text/css">
		<script>
			$(document).ready(function() {
				$('.popup-with-zoom-anim').magnificPopup({
					type: 'inline',
					fixedContentPos: false,
					fixedBgPos: true,
					overflowY: 'auto',
					closeBtnInside: true,
					preloader: false,
					midClick: true,
					removalDelay: 300,
					mainClass: 'my-mfp-zoom-in'
			});
		});
		</script>
           </div>
		   <div class="clear"></div>	
		  </div>
	</div>	
   </div> 

app/views/home/contacto.html.erb
       <div class="login">
          <div class="wrap">
				<ul class="breadcrumb breadcrumb__t"><%= link_to "Home", root_path, {:style => 'background:#f7f7f7'} %>  / Políticas de privacidad</ul>

				    <div class="cont span_2_of_about">
				       <h3>Políticas de privacidad</h3>
				       <br>
				       <h3>Derechos de acceso, cancelación y rectificación de la información personal</h3>
				       <p>
				       	Los usuarios tienen derechos reconocidos y podrán ejercitar los derechos de acceder, cancelar y actualizar su Información Personal, incluyendo su dirección de e-mail, así como a oponerse al tratamiento de la misma y a ser informado de las cesiones llevadas a cabo, todo ello de conformidad a lo dispuesto en la normativa aplicable. Los usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de la Información Personal facilitada, y se comprometen a mantenerla debidamente actualizada.
						Una vez inscrito en Smarket, el usuario podrá revisar y cambiar la información que nos ha enviado durante el proceso de inscripción incluyendo:
						<br>
						El Seudónimo y dirección de correo electrónico. Sin perjuicio de los cambios que realice, Smarket conservará la Información Personal anterior por motivos de seguridad y control del fraude.
						<br>
						La información de la inscripción como: compañía, domicilio, ciudad, región, código postal, número principal de teléfono, número secundario de teléfono, número de fax, correo electrónico, etc.
						<br>
						La clave.
						<br>
						En determinados casos, mantendremos en nuestros archivos Información Personal que nos hayas pedido que retiremos, y ello con la finalidad de resolver disputas o reclamaciones, detectar problemas o incidencias y solucionarlos, y dar cumplimiento a lo dispuesto en los Términos y Condiciones Generales por un período de tiempo determinado por la ley. En cualquier caso, la Información Personal de un usuario no será inmediatamente retirada de nuestros archivos por motivos legales y técnicos, incluyendo sistemas de soportes de seguridad. Por tanto, no se debe esperar que toda la Información Personal sea definitivamente borrada de nuestras bases de datos.
						Los usuarios deben actualizar su Información Personal periódicamente conforme vaya cambiando para que los otros usuarios puedan ubicarlos cuando realicen una operación. Para hacer cualquier modificación en la información que suministrada en el momento de la Inscripción, se debe ingresar en la sección Mi Smarket y hacer clic en Mis Datos.
						Smarket podrá modificar en cualquier momento los términos y condiciones de estas Políticas de Privacidad y confidencialidad y/o las prácticas de envío de e-mails. Si decidimos introducir algún cambio material a nuestras Políticas de Privacidad, te notificaremos publicando una versión actualizada de las Políticas en esta sección o mediante el envío de un e-mail o informándolo en la página principal u otras secciones del sitio para mantenerte actualizado de los cambios realizados.
						Si hacemos cambios materiales en la forma que tu Información Personal es administrada te notificaremos por e-mail para que puedas tomar una decisión informada respecto si aceptas o no que tu Información Personal sea utilizada de esa forma. Si no aceptas esos términos, en ese caso quedará disuelto el vínculo contractual y tu Información Personal no será usada de otra forma que la que fue informada al momento de recabarse.
				       </p>
				       <br>
				       <h3>Uso que hacemos de la información</h3>
				       <p>
				       	Para suministrar un excelente servicio y para que los usuarios puedan realizar operaciones en forma ágil y segura, Smarket requiere cierta información de carácter personal, incluyendo dirección de e-mail. La recolección de información nos permite ofrecer a los usuarios servicios y funcionalidades que se adecuen mejor a sus necesidades y personalizar nuestros servicios para hacer que sus experiencias con Smarket sean lo más cómodas posible. La Información Personal que recabamos tiene las siguientes finalidades:
						Ayudar al comprador y vendedor a entrar en contacto directo en la oportunidad que corresponda según la modalidad de la compra. En este caso, Smarket suministrará a los interesados sus datos personales (nombre, teléfonos, localidad y correo electrónico), a través de correo electrónico o a través del sitio. La información así conocida por el comprador o el vendedor, sólo podrá ser utilizada a efectos de concluir la operación originada en Smarket y no deberá ser empleada por ninguno de ellos con fines publicitarios o promocionales u otras actividades no relacionadas con Smarket, salvo la expresa autorización del usuario.
						Desarrollar estudios internos sobre los intereses, comportamientos y demografía de los usuarios para comprender mejor sus necesidades e intereses y proveerles información relacionada.
						Mejorar nuestras iniciativas comerciales y promocionales y analizar las páginas visitadas las búsquedas realizadas por los usuarios, para mejorar nuestra oferta de contenidos y artículos, personalizar dichos contenidos y su presentación .
						Mostrar publicidad o promociones, banners, de interés para nuestros usuarios, noticias sobre Smarket, además de la información expresamente autorizada en la sección de preferencias. Si el usuario lo prefiere, puede solicitar que lo excluyan de las listas para el envío de información promocional o publicitaria. 
						Compartir la información Personal (incluyendo dirección de e-mail) con los proveedores de servicios o las empresas de "outsourcing" que contribuyan a mejorar o facilitar las operaciones a través de Smarket, como medios de pago, seguros o intermediarios en la gestión de pagos, call centers o programas de fidelidad, entre otros. Smarket velará porque se cumplan ciertos estándares, mediante la firma de acuerdos o convenios cuyo objeto sea la privacidad de los datos personales de nuestros usuarios. No obstante, Smarket no se hace responsable por el uso indebido de la Información Personal del usuario que hagan estas compañías o sitios de Internet. En algunos casos, estos proveedores de servicios serán quienes recojan información directamente del usuario (por ejemplo si les solicitamos que realicen encuestas o estudios). En tales casos, podrá recibir una notificación acerca de la participación de un proveedor de servicios en tales actividades, y quedará a discreción del usuario toda la información que quiera brindarle y los usos adicionales que los proveedores decidan hacer. En caso de que facilites, por propia iniciativa información adicional a dichos prestadores de servicios directamente, tales Prestadores usarán esta información conforme a sus propias políticas de privacidad. Si decidimos revelar o compartir Información Persona con terceros que no son proveedores de servicios o empresas afiliadas o relacionadas con Smarket, requeriremos tu consentimiento.

						Suministrar la información personal de los usuarios a las entidades que intervengan en la resolución de disputas entre los mismos, tales como: Compañías de Seguros, Amigables Componedores o Tribunales de Arbitraje o tribunales competentes para solucionar tales disputas. 
				       </p>
				       <br>
				       <h3>Confidencialidad de la información</h3>
				       <p>
				       	Una vez inscrito en su sitio Web, Smarket no venderá, alquilará o compartirá la Información Personal excepto en las formas establecidas en estas políticas. Sin perjuicio de ello, el usuario consiente en forma expresa que Smarket transfiera total o parcialmente la Información Personal a cualquiera de las sociedades controladas, controlantes y/o vinculadas con Smarket, a cualquier título y en el momento, forma y condiciones que estime pertinentes. Haremos todo lo que esté a nuestro alcance para proteger la privacidad de la información. Puede suceder que en virtud de órdenes judiciales, o de regulaciones legales, nos veamos compelidos a revelar información a las autoridades o terceras partes bajo ciertas circunstancias, o bien en casos que terceras partes puedan interceptar o acceder a cierta información o transmisiones de datos en cuyo caso Smarket no responderá por la información que sea revelada.
				       </p>
				       <br>
				       <h3>Menores de Edad</h3>
				       <p>
				       	Nuestros servicios sólo están disponibles para aquellas personas que tengan capacidad legal para contratar. Por lo tanto, aquellos que no cumplan con esta condición deberán abstenerse de suministrar información personal para ser incluida en nuestras bases de datos. Sin embargo, pueden hacerlo a través de los padres o tutores.
				       </p>
				       <br>
				       <h3>El uso de la información por otros usuarios</h3>
				       <p>
				       	Para facilitar la interacción entre todos los miembros de la comunidad de Smarket, nuestro servicio permite un acceso limitado a ciertos datos de contacto del resto de usuarios, tales como Nombre de usuario, Teléfonos, Ciudad y dirección de correo electrónico.
						Los usuarios sólo podrán utilizar la Información Personal de otros usuarios obtenida en el sitio para: (a) comunicaciones relacionadas con Smarket que no constituyan comunicaciones comerciales no solicitadas, (b) utilizar servicios ofrecidos en Smarket (por ejemplo: depósito, seguros, envío o transporte y reclamaciones sobre fraude), y (c) cualquier otra finalidad a la que el usuario correspondiente consienta expresamente una vez le hayan sido comunicadas previamente la información legalmente requerida.
						Bajo ninguna circunstancia, se debe comunicar Información Personal o dirección de correo electrónico de otro usuario a ningún tercero sin nuestro consentimiento y el del usuario afectado. No se debe agregar a la agenda de direcciones de correo electrónico (física o electrónica) los datos de ningún usuario de Smarket, ni siquiera los datos de quienes hayan adquirido algún artículo ofrecido en Smarket, sin que medie el consentimiento expreso de tal usuario.
				       </p>
				        
							
		   </div>
		   <!-- Add fancyBox main JS and CSS files -->
		<script src="js/jquery.magnific-popup.js" type="text/javascript"></script>
		<link href="css/magnific-popup.css" rel="stylesheet" type="text/css">
		<script>
			$(document).ready(function() {
				$('.popup-with-zoom-anim').magnificPopup({
					type: 'inline',
					fixedContentPos: false,
					fixedBgPos: true,
					overflowY: 'auto',
					closeBtnInside: true,
					preloader: false,
					midClick: true,
					removalDelay: 300,
					mainClass: 'my-mfp-zoom-in'
			});
		});
		</script>
           </div>
		   <div class="clear"></div>	
		  </div>
	</div>	
   </div> 

app/views/home/index.html.erb
<br>
<%
   base_url = request.url
   if request.path != '/'
       base_url = base_url.gsub(request.path, '')
   end
%> 


<div id="fwslider">
        <div class="slider_container">
            <div class="slide"> 
                <!-- Slide image -->
                <%= image_tag("banner.jpg")%>  
                <!-- /Slide image -->
                <!-- Texts container -->
                <div class="slide_content">
                    <div class="slide_content_wrap">
                        <!-- Text title -->
                        <h4 class="title">Vende tus productos</h4>
                        <!-- /Text title -->
                        
                        <!-- Text description -->
                        <p class="description">Oferta tus necesidades</p>
                        <!-- /Text description -->
                    </div>
                </div>
                 <!-- /Texts container -->
            </div>
            <!-- /Duplicate to create more slides -->
            <div class="slide">
                <%= image_tag("banner1.jpg") %>
                <div class="slide_content">
                    <div class="slide_content_wrap">
                        <h4 class="title">Crea remates</h4>
                        <p class="description">Compra en línea</p>
                    </div>
                </div>
            </div>
            <!--/slide -->
        </div>
        <div class="timers"></div>
        <div class="slidePrev"><span></span></div>
        <div class="slideNext"><span></span></div>
    </div>
    <!--/slider -->

    
    <!-- MAIN -->
    <div class="main">
    <div class="wrap">
    <div class="section group">
      <div class="cont span_2_of_3">
        <h2 class="head">Ofertas</h2>
       
      <h2 class="head">Necesidades</h2>
           
        <div class="clear"></div>
      </div>  
 
        
        <div class="clear"></div>
      </div>                            
      </div>
      <div class="rsidebar span_1_of_left">


      <div class="top-border"> </div>
      <div class="sidebar-bottom">
        <% if usuario_signed_in? %>
          <h2 class="m_1">Bienvenido <%= current_usuario.usuario_nombre_usuario %></h2>
          <p>
            Comienza a comprar y vender tus productos sin esperar más. No dejes pasar una gran oportunidad.
          </p>
        <% else %>
          <h2 class="m_1"><%= link_to "Login", new_usuario_session_path, {:style => 'background: #555;
                                    border:none;
                                    color: #fff;
                                    padding: 10px 20px;
                                    cursor: pointer;
                                    font-family: "Exo 2", sans-serif;
                                    outline: none;
                                    font-size: 1em;
                                    border-radius: 10px'} %></h2><br><br>
          <h2 class="m_1"><%= link_to "Sign up", new_usuario_registration_path, {:style =>  'background: #555;
                                    border:none;
                                    color: #fff;
                                    padding: 10px 20px;
                                    cursor: pointer;
                                    font-family: "Exo 2", sans-serif;
                                    outline: none;
                                    font-size: 1em;
                                    border-radius: 10px'} %></h2>
        <% end %>
      </div>
      </div>
     <div class="clear"></div>
  </div>
  </div>
  </div>





    <!-- FOOTER -->
       <div class="footer">

        <div class="footer-middle">
            <div class="wrap">
             
           <div class="footer-bottom">
            <div class="wrap">
                 <div class="copy">
                    <p>© Smarket 2014</p>
                 </div>
                <div class="f-list2">
                 <ul>
                    <li class="active"><%= link_to "Sobre nosotros", home_about_path, {:style => 'background: #0b4b5a'}%></li> |
                    <li><%= link_to "Terminos y condiciones", home_terminos_path, {:style => 'background: #0b4b5a'}%></li> |
                    <li><%= link_to "Políticas de privacidad", home_contacto_path, {:style => 'background: #0b4b5a'}%></li> 
                    <li><%= link_to "Como comprar", home_comocomprar_path, {:style => 'background:#0b4b5a'}%></li>
                            <li><%= link_to "Como vender", home_comovender_path, {:style => 'background:#0b4b5a'}%></li>
                            <li><%= link_to "Mi cuenta", home_datoscuenta_path, {:style => 'background:#0b4b5a'}%></li>
                 </ul>
                </div>


                <div class="company_address"> <br>
                            <p>Universidad de Santiago de Chile</p>
                            <p>Departamento de Ingeniería Informática</p>
                            <p>Chile</p>
                            <p>Telefono:(+569) 95438543</p>
                            <p>Email: <span>smarket@usach.cl</span></p>
                            
                       </div>
                <div class="clear"></div>

              </div>
         </div>
    </div>