config/routes.rb
Smarket::Application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "home/datoscuenta"
  get "home/comovender"
  get "home/comocomprar"
  get "home/perfil"
  get "home/about"
  get "home/contacto"
  get "home/terminos"
  get "home/index"
  resources :tipo_transaccions

  resources :producto_rematados

  resources :provincia_units

  resources :propiedadclases

  resources :compra_venta_normals

  resources :clase_units

  resources :prod_of_necs

  resources :compra_venta_especials

  resources :producto_necesitados

  resources :compra_remates

  resources :notificacions

  resources :comisions

  resources :remates

  resources :pujas

  resources :valors

  resources :usuarios

  resources :propiedads

  resources :regions

  resources :productos

  resources :estado_remates

  resources :ganancia_liquidas

  resources :est_prod_of_necs

  resources :estado_notificacions

  resources :producto_ofertados

  resources :comunas

  resources :condicions


  root :to => "home#index"
  devise_for :usuarios, :controllers => { registrations: 'registrations' }, :skip => [:sessions, :registrations] 
  as :usuario do
    get    "entrar",  to: "devise/sessions#new",         :as => :new_usuario_session
    post   "entrar",  to: "devise/sessions#create",      :as => :usuario_session
    delete "salir", to: "devise/sessions#destroy",     :as => :destroy_usuario_session
 
    get    "registrarse",  to: "devise/registrations#new",    :as => :new_usuario_registration
    post   "registrarse",  to: "devise/registrations#create", :as => :usuario_registration
  end
  
  
end

app/models/producto_rematado.rb
class ProductoRematado < ActiveRecord::Base
  self.table_name = 'producto_rematado'
  self.primary_key = 'id'
  #inherits_from :producto
  has_one :compra_remate
end

app/controllers/producto_rematados_controller.rb
class ProductoRematadosController < ApplicationController
  before_action :set_producto_rematado, only: [:show, :edit, :update, :destroy]

  # GET /producto_rematados
  # GET /producto_rematados.json
  def index
    @producto_rematados = ProductoRematado.all
  end

  # GET /producto_rematados/1
  # GET /producto_rematados/1.json
  def show
  end

  # GET /producto_rematados/new
  def new
    @producto_rematado = ProductoRematado.new
  end

  # GET /producto_rematados/1/edit
  def edit
  end

  # POST /producto_rematados
  # POST /producto_rematados.json
  def create
    @producto_rematado = ProductoRematado.new(producto_rematado_params)

    respond_to do |format|
      if @producto_rematado.save
        format.html { redirect_to @producto_rematado, notice: 'Producto rematado was successfully created.' }
        format.json { render action: 'show', status: :created, location: @producto_rematado }
      else
        format.html { render action: 'new' }
        format.json { render json: @producto_rematado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /producto_rematados/1
  # PATCH/PUT /producto_rematados/1.json
  def update
    respond_to do |format|
      if @producto_rematado.update(producto_rematado_params)
        format.html { redirect_to @producto_rematado, notice: 'Producto rematado was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @producto_rematado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producto_rematados/1
  # DELETE /producto_rematados/1.json
  def destroy
    @producto_rematado.destroy
    respond_to do |format|
      format.html { redirect_to producto_rematados_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto_rematado
      @producto_rematado = ProductoRematado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_rematado_params
      params.require(:producto_rematado).permit(:producto_id, :prod_sub_id, :prod_sub_cantidad, :prod_sub_precio_unitario)
    end
end

app/helpers/producto_rematados_helper.rb
module ProductoRematadosHelper
end

app/views/producto_rematados/_form.html.erb
<%= form_for(@producto_rematado) do |f| %>
  <% if @producto_rematado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto_rematado.errors.count, "error") %> prohibited this producto_rematado from being saved:</h2>

      <ul>
      <% @producto_rematado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :producto_id %><br>
    <%= f.text_field :producto_id %>
  </div>
  <div class="field">
    <%= f.label :prod_sub_id %><br>
    <%= f.text_field :prod_sub_id %>
  </div>
  <div class="field">
    <%= f.label :prod_sub_cantidad %><br>
    <%= f.number_field :prod_sub_cantidad %>
  </div>
  <div class="field">
    <%= f.label :prod_sub_precio_unitario %><br>
    <%= f.number_field :prod_sub_precio_unitario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/producto_rematados/edit.html.erb
<h1>Editing producto_rematado</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto_rematado %> |
<%= link_to 'Back', producto_rematados_path %>

app/views/producto_rematados/index.html.erb
<h1>Listing producto_rematados</h1>

<table>
  <thead>
    <tr>
      <th>Producto</th>
      <th>Prod sub</th>
      <th>Prod sub cantidad</th>
      <th>Prod sub precio unitario</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @producto_rematados.each do |producto_rematado| %>
      <tr>
        <td><%= producto_rematado.producto %></td>
        <td><%= producto_rematado.prod_sub %></td>
        <td><%= producto_rematado.prod_sub_cantidad %></td>
        <td><%= producto_rematado.prod_sub_precio_unitario %></td>
        <td><%= link_to 'Show', producto_rematado %></td>
        <td><%= link_to 'Edit', edit_producto_rematado_path(producto_rematado) %></td>
        <td><%= link_to 'Destroy', producto_rematado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto rematado', new_producto_rematado_path %>

app/views/producto_rematados/new.html.erb
<h1>New producto_rematado</h1>

<%= render 'form' %>

<%= link_to 'Back', producto_rematados_path %>

app/views/producto_rematados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Producto:</strong>
  <%= @producto_rematado.producto %>
</p>

<p>
  <strong>Prod sub:</strong>
  <%= @producto_rematado.prod_sub %>
</p>

<p>
  <strong>Prod sub cantidad:</strong>
  <%= @producto_rematado.prod_sub_cantidad %>
</p>

<p>
  <strong>Prod sub precio unitario:</strong>
  <%= @producto_rematado.prod_sub_precio_unitario %>
</p>

<%= link_to 'Edit', edit_producto_rematado_path(@producto_rematado) %> |
<%= link_to 'Back', producto_rematados_path %>