config/routes.rb
Smarket::Application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "home/datoscuenta"
  get "home/comovender"
  get "home/comocomprar"
  get "home/perfil"
  get "home/about"
  get "home/contacto"
  get "home/terminos"
  get "home/index"
  resources :tipo_transaccions

  resources :producto_rematados

  resources :provincia_units

  resources :propiedadclases

  resources :compra_venta_normals

  resources :clase_units

  resources :prod_of_necs

  resources :compra_venta_especials

  resources :producto_necesitados

  resources :compra_remates

  resources :notificacions

  resources :comisions

  resources :remates

  resources :pujas

  resources :valors

  resources :usuarios

  resources :propiedads

  resources :regions

  resources :productos

  resources :estado_remates

  resources :ganancia_liquidas

  resources :est_prod_of_necs

  resources :estado_notificacions

  resources :producto_ofertados

  resources :comunas

  resources :condicions


  root :to => "home#index"
  devise_for :usuarios, :controllers => { registrations: 'registrations' }, :skip => [:sessions, :registrations] 
  as :usuario do
    get    "entrar",  to: "devise/sessions#new",         :as => :new_usuario_session
    post   "entrar",  to: "devise/sessions#create",      :as => :usuario_session
    delete "salir", to: "devise/sessions#destroy",     :as => :destroy_usuario_session
 
    get    "registrarse",  to: "devise/registrations#new",    :as => :new_usuario_registration
    post   "registrarse",  to: "devise/registrations#create", :as => :usuario_registration
  end
  
  
end

app/models/producto_ofertado.rb
class ProductoOfertado < ActiveRecord::Base
  self.table_name = 'producto_ofertado'
  self.primary_key = 'producto_of_id '
  #inherits_from :producto
  belongs_to :usuario
  belongs_to :compra_venta_normal
  belongs_to :producto

end

app/controllers/producto_ofertados_controller.rb
class ProductoOfertadosController < ApplicationController
  before_filter :authenticate_usuario!,except:[:index]
  before_action :set_producto_ofertado, only: [:show, :edit, :update, :destroy]

  # GET /producto_ofertados
  # GET /producto_ofertados.json
  def index
    
    @producto_ofertados = ProductoOfertado.all
  end

  # GET /producto_ofertados/1
  # GET /producto_ofertados/1.json
  def show

  end

  # GET /producto_ofertados/new
  def new
    @producto_ofertados= ProductoOfertado.where(usuario_id:current_usuario.id)
    @clase_unit = nil
    @clase_units = ClaseUnit.find(:all, :conditions => {:cla_clase_id => nil } )
    @producto = Producto.new
    @producto.producto_ofertados.build
  end

  # GET /producto_ofertados/1/edit
  def edit
  end

  # POST /producto_ofertados
  # POST /producto_ofertados.json
  def create
    @producto = Producto.new(producto_params)
    @producto.save!


    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto_ofertado, notice: 'Producto ofertado was successfully created.' }
        format.json { render action: 'show', status: :created, location: @producto_ofertado }
      else
        format.html { render action: 'new' }
        format.json { render json: @producto_ofertado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /producto_ofertados/1
  # PATCH/PUT /producto_ofertados/1.json
  def update
    @producto_ofertado= @producto.producto_ofertados.find(params[:id]) 
    if @producto_ofertado.update_attributes(params[:producto_ofertado])
      redirect_to producto_ofertado_path :notice  => "Successfully updated quotation."
    else
      render :action => 'edit'
    end
    
    #respond_to do |format|
     # if @producto_ofertado.update(producto_ofertado_params)
      #  format.html { redirect_to @producto_ofertado, notice: 'Producto ofertado was successfully updated.' }
       
       # format.json { head :no_content }
      #else
       # format.html { render action: 'edit' }
        #format.json { render json: @producto_ofertado.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # DELETE /producto_ofertados/1
  # DELETE /producto_ofertados/1.json
  def destroy
    @producto_ofertado.destroy
    respond_to do |format|
      format.html { redirect_to producto_ofertados_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto_ofertado
      @producto_ofertado = ProductoOfertado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:producto_id, :clase_id,   :producto_nombre, :avatar, producto_ofertados_attributes:[:producto_id, :producto_of_id,:usuario_id, :producto_of_cantidad, :producto_of_precio_unitario, :producto_of_fecha_publicacion])
    end
    def producto_ofertado_params
      params.require(:producto_ofertado).permit(:producto_id, :producto_of_id,:usuario_id, :producto_of_cantidad, :producto_of_precio_unitario, :producto_of_fecha_publicacion)
    end
end

app/helpers/producto_ofertados_helper.rb
module ProductoOfertadosHelper
end

app/views/producto_ofertados/_form.html.erb
<%= form_for(@producto) do |f| %>

<div class="field">
 <%= f.label :Ingrese_la_categoría_en_la_que_usted_cree_que_se_encuentra_su_producto %><br>

  
  <script type="text/javascript">
  $(function(){
    var cambio = false
    var cambios_en_subcategoria = false;
    var categoriasPri = {
    <% @clase_units.each do | clase_unit | %>
       "<%= clase_unit.clase_nombre.html_safe %>":{
          <% clase_unit.subcategorias.each do | subcategoria | %>
             "<%= subcategoria.clase_nombre.html_safe %>":{
              <% subcategoria.subcategorias.each do |subsubcategoria| %>
                  <%= subsubcategoria.clase_id %>:"<%= subsubcategoria.clase_nombre %>",
              <%end%>
              },     
          <%end%> 
        },
    <%end%>
  };
    $('#categoria').on('change', function(){        
        html = ''
        categoria_seleccionada = $('#categoria option:selected').text()
        $.each(categoriasPri[categoria_seleccionada],function(key){
          html += '<option>' + key + '</option>'
        });      
        $('#subcategoria').html(html);
        $('#subcategoria').prop("disabled", false);
        $('#subsubcategoria').prop("disabled", true);
        cambios_en_subcategoria = true;
      })
      $('#subcategoria').on('change',function(){
        html=''
        categoria_seleccionada = $('#categoria option:selected').text()
        subcategoria_seleccionada = $('#subcategoria option:selected').text()
        $.each(categoriasPri[categoria_seleccionada][subcategoria_seleccionada], function(key,value){
          html += '<option value="' + key+ '">' + value + '</option>'
          if(categoriasPri[categoria_seleccionada][subcategoria_seleccionada]!=null)
            cambio = true
        });
        console.log(cambio)
        $('#subsubcategoria').html(html);
        if(cambio==false)
          $('#subsubcategoria').prop("disabled", true);
        else
          if(cambios_en_subcategoria)
            $('#subsubcategoria').prop("disabled", false);
        cambio = false
      })
})
</script>



<% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>

  <div class="field">
    <%= f.label :Seleccione_una_imagen_para_su_producto %><br />
    <%= f.file_field :avatar %>
  </div>

   
<select id="categoria" size=20 style="height: 40%">
      <% @clase_units.each do |clase_unit| %>
          <option value = "<%=clase_unit.clase_id%>"><%= clase_unit.clase_nombre %></option>
      <% end %>  
 </select>

<select id="subcategoria" name= 'producto[clase_id]' size=20 style='height: 40%' disabled>
</select>

<select id="subsubcategoria" name= 'producto[clase_id]'size=20 style='height: 40%' disabled>
<br> 
</div>
 <br> 
 
<div class ="field">
  <br> <%= f.label :producto_nombre , 'Nombre del producto'%><br>
        <%= f.text_field :producto_nombre %>
</div>

<%= f.fields_for :producto_ofertados do |fa| %>
  <div class="field">
      <br> <%= fa.label :producto_of_cantidad, 'Cantidad de productos'%><br>
      <%= fa.number_field :producto_of_cantidad %>
  </div>
  <div class="field">
    <%= fa.label :producto_of_precio_unitario, 'Precio Unitario' %><br>
    <%= fa.number_field :producto_of_precio_unitario %>
  </div>

  <% end %>



  <div class="actions">
    <p><%= f.submit "Ofertar producto" %></p>
  </div>
<% end %>

app/views/producto_ofertados/edit.html.erb
<h1>Editing producto_ofertado</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto_ofertado %> |
<%= link_to 'Back', producto_ofertados_path %>

app/views/producto_ofertados/index.html.erb
<div style="padding-left:100px">
  <h1 style="font-size:40px">OFERTAS</h1><br>
  <style>
  table,th,td
  {
  border:0px solid black;
  }
  th,td
  {
  padding:15px;
  }
  thead
  {
  background:#4cb1ca;
  color: #fff;

  }
  </style>
  <table style="width:90%">
    <thead style="width:100%">
      <tr>
        <th>Producto</th>
        <th>Producto of</th>
        <th>Usuario</th>
        <th>Cantidad</th>
        <th>Precio</th>
        <th>Fecha de publicacion</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @producto_ofertados.each do |producto_ofertado| %>
        <tr>
          <td><%= producto_ofertado.producto %></td>
          <td><%= producto_ofertado.producto_of %></td>
          <td><%= producto_ofertado.usuario %></td>
          <td><%= producto_ofertado.producto_of_cantidad %></td>
          <td><%= producto_ofertado.producto_of_precio_unitario %></td>
          <td><%= producto_ofertado.producto_of_fecha_publicacion %></td>
          <td><%= link_to 'Show', producto_ofertado %></td>
          <td><%= link_to 'Edit', edit_producto_ofertado_path(producto_ofertado) %></td>
          <td><%= link_to 'Destroy', producto_ofertado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if usuario_signed_in? %>
    <%= link_to 'Publica tu Oferta', new_producto_ofertado_path, :style =>  'background: #555;
                                    border:none;
                                    color: #fff;
                                    padding: 10px 20px;
                                    cursor: pointer;
                                    font-family: "Exo 2", sans-serif;
                                    outline: none;
                                    font-size: 1em' %>
  <% else %>
    <%= link_to 'Publica tu Oferta', new_usuario_session_path, :style =>  'background: #555;
                                    border:none;
                                    color: #fff;
                                    padding: 10px 20px;
                                    cursor: pointer;
                                    font-family: "Exo 2", sans-serif;
                                    outline: none;
                                    font-size: 1em' %>
    <% end %>
</div>

app/views/producto_ofertados/new.html.erb
<div style="padding-left:100px">
<h1 style="font-size:40px">Ingresar Producto</h1>
<br>
<%= render 'form' %>

<%= link_to 'Back', producto_ofertados_path %>
<br>
</div>

app/views/producto_ofertados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Producto:</strong>
  <%= @producto_ofertado.producto %>
</p>

<p>
  <strong>Producto of:</strong>
  <%= @producto_ofertado.producto_of %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @producto_ofertado.usuario %>
</p>

<p>
  <strong>Producto of cantidad:</strong>
  <%= @producto_ofertado.producto_of_cantidad %>
</p>

<p>
  <strong>Producto of precio unitario:</strong>
  <%= @producto_ofertado.producto_of_precio_unitario %>
</p>

<p>
  <strong>Producto of fecha publicacion:</strong>
  <%= @producto_ofertado.producto_of_fecha_publicacion %>
</p>

<%= link_to 'Edit', edit_producto_ofertado_path(@producto_ofertado) %> |
<%= link_to 'Back', producto_ofertados_path %>